### ISSUE TITLE
目前还不支持播放列表(类似jwplayer的playlist)吗？

### ISSUE THREAD

**Issue by oulaly** [alilmq/livedemo#2]
文档和demo中都没有找到。后续会支持吗？

另外，在尝试一个页面两个实例时，有一个实例播放异常。

**Comment by alilmq** [comment]
这个要自己实现，https://github.com/alilmq/h5demo 这个有列表的demo，  播放异常具体什么异常， 如果两个实例，需要id不一样

**Comment by oulaly** [comment]
这个demo不是播放器内置播放列表的效果。

v2.2.0，两个实例的ID是不一样的，播放源相同，第一个实例一直处于加载中，第二个实例正常播放。

> aliplayer-min.js:3 Uncaught TypeError: Cannot read property 'startLoad' of null
        at c.b.play (aliplayer-min.js:3)
        at c.<anonymous> (aliplayer-min.js:4)
        at HTMLDivElement.e (aliplayer-min.js:1)
        at HTMLDivElement.h.dispatcher.h.dispatcher (aliplayer-min.js:1)
b.play @ aliplayer-min.js:3
(anonymous) @ aliplayer-min.js:4
e @ aliplayer-min.js:1
h.dispatcher.h.dispatcher @ aliplayer-min.js:1

**Comment by alilmq** [comment]
可以先用下面的workround方法，后面会修改这个问题

`

           var player1;
           var player = new Aliplayer({
           id: 'J_prismPlayer1',
            width: '40%',
            height: '50%',
            autoplay: true,
            source:"",
        
            });
            player.on('play',function(){
                var player1 = new Aliplayer({
                id: 'J_prismPlayer',
                width: '40%',
                height: '50%',
                autoplay: true,
                source:"",
            
                });
            })

`

**Comment by oulaly** [comment]
好的，谢谢!
