### ISSUE TITLE
两个相同的播放器，前面一个不会播放

### ISSUE THREAD

**Issue by Statfine** [alilmq/livedemo#3]
同一个页面有两个相同配置的播放器，则后面的播放器正常，前面的播放器不会播放
![1514443133240](https://user-images.githubusercontent.com/4608910/34402500-de78700e-ebdc-11e7-8fc1-e05558b3efaa.jpg)

**Comment by alilmq** [comment]
我试过可以的， 你的id不一样的吧？

**Comment by Statfine** [comment]
`
      <div>
        <Player playId="palyOne" url="http://alcdn.hls.xiaoka.tv/20171226/298/b36/KhW9oREcf_BTjYpZ/index.m3u8" />
        <Player playId="palyTwo" url="http://alcdn.hls.xiaoka.tv/20171226/298/b36/KhW9oREcf_BTjYpZ/index.m3u8" />
      </div>
`

player.js
componentDidMount() {
    this.initPlayer(this.props.url);
  }
  initPlayer = (url) => {
    this.playLiveOne = new Aliplayer({ // eslint-disable-line
      id: this.props.playId, // 容器id
      isLive: false,
      autoplay: true,      // 自动播放
      useH5Prism: true,
      useFlashPrism: url.endsWith('flv'),
      source: url,         // 视频url 支持互联网可直接访问的视频地址
      width: '420px',       // 播放器宽度
      height: '260px',      // 播放器高度
    });
  };
  render() {
    console.log('id:', this.props.playId);
    return (
      <div>
        <div id={this.props.playId} />
      </div>
    );
  }
![1516609728056](https://user-images.githubusercontent.com/4608910/35211583-0d66b01a-ff92-11e7-87d6-69fd354de43b.jpg)
@alilmq

**Comment by alilmq** [comment]
写了一下例子，放了4个播放器，也可以正常播放的， 查看附件

[twoplayer.html.zip](https://github.com/alilmq/livedemo/files/1659725/twoplayer.html.zip)

**Comment by Statfine** [comment]
@alilmq  MP4是正常可以的， 您source换成直播流m3u8的好像就不行了，可以试试

**Comment by Statfine** [comment]
@alilmq  是否存在两个播放器不能同时播放m3u8，还是我的配置错误了

**Comment by alilmq** [comment]
上面的例子用m3u8也是可以的
![default](https://user-images.githubusercontent.com/29850435/35608349-b7256b3e-0693-11e8-90a0-a24b5125fdd0.png)

**Comment by Statfine** [comment]
[index.html.zip](https://github.com/alilmq/livedemo/files/1680778/index.html.zip)
![1517384363717](https://user-images.githubusercontent.com/4608910/35610615-f16246b0-069c-11e8-8be4-be88e1cbe51f.jpg)
还是麻烦看看了

**Comment by alilmq** [comment]
我看你用的是2..4.0版本， 用新的2.5.0版本

**Comment by Statfine** [comment]
2.5.0版本可以

**Comment by oulaly** [comment]
和我之前遇到的问题一样 #2

**Comment by Statfine** [comment]
@oulaly  版本的bug吧，升级之后就好了

**Comment by oulaly** [comment]
是的，我之前用的2.2的版本
